description_transactions = [
    "ABONO INTERESES AHORROS",
    "PAGO PSE BANCO DAVIVIENDA SA",
    "ABONO INTERESES AHORROS",
    "CUOTA MANEJO TARJETA DEBITO",
    "PAGO INTERBANC WIZELINE SAS",
    "TRANSFERENCIA CTA SUC VIRTUAL",
    "PAGO SUC VIRT TC VISA",
    "PAGO PSE P.A. ADDI",
    "PAGO PSE Portal Zona Pagos BB",
    "PAGO PSE NU COLOMBIA SA",
    "PAGO PSE Acueducto Metropolit",
    "PAGO SUC VIRT TC AMEX PESOS",
    "PAGO SUC VIRT TC AMEX DOLAR",
    "TRANSFERENCIA CTA SUC VIRTUAL"
]

